"""Updated models

Revision ID: 4094f45faa48
Revises: 8fe80f1788f2
Create Date: 2026-02-07 16:50:43.829962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4094f45faa48'
down_revision = '8fe80f1788f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('recipeTags')
    op.drop_table('currentIngredients')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('unit')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1500), nullable=False))
        batch_op.add_column(sa.Column('servingSize', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('estimatedTime', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('steps', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False))
        batch_op.drop_column('body')
        batch_op.drop_column('saves')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('saves', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=1500), nullable=False))
        batch_op.drop_column('is_draft')
        batch_op.drop_column('steps')
        batch_op.drop_column('estimatedTime')
        batch_op.drop_column('servingSize')
        batch_op.drop_column('description')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))

    op.create_table('currentIngredients',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ingredient_id')
    )
    op.create_table('recipeTags',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    # ### end Alembic commands ###
