"""Limit of desc to 215

Revision ID: 71d34a2a60c5
Revises: aba35ca10a72
Create Date: 2026-02-15 14:49:55.042906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d34a2a60c5'
down_revision = 'aba35ca10a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=210),
               type_=sa.String(length=215),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=215),
               type_=sa.VARCHAR(length=210),
               existing_nullable=False)

    # ### end Alembic commands ###
