"""Added description to recipe table

Revision ID: 93a2fd0cc14b
Revises: 8fe80f1788f2
Create Date: 2026-02-08 18:58:37.896432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a2fd0cc14b'
down_revision = '8fe80f1788f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
