"""Limited desc to 210 characters

Revision ID: aba35ca10a72
Revises: 8146501a941a
Create Date: 2026-02-15 14:45:15.192988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba35ca10a72'
down_revision = '8146501a941a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=215),
               type_=sa.String(length=210),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=210),
               type_=sa.VARCHAR(length=215),
               existing_nullable=False)

    # ### end Alembic commands ###
