"""Re added timestamp for recipe

Revision ID: e83d7cb8526e
Revises: 4094f45faa48
Create Date: 2026-02-07 16:53:01.731988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83d7cb8526e'
down_revision = '4094f45faa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
